#nextjs 9500
#ws 9600
#postgre 9700

services:
  next:
    restart: always
    build:
      context: ./
    command: npm run start-all
    ports:
      - "9500:3000"
      - "9600:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXT_PUBLIC_WEBSOCKET_URL: ${NEXT_PUBLIC_WEBSOCKET_URL}
      WEBSOCKET_PORT: ${WEBSOCKET_PORT}
      APP_URL: ${APP_URL}
    network_mode: host
